import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Poppins } from "next/font/google";
import "./../globals.css";

import Header from "@/components/header/Header";
import NavArea from "@/components/header/NavArea";
import Footer from "@/components/footer/Footer";
import CopyrightInfo from "@/components/footer/CopyrightInfo";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import connectDB from "@/lib/db";
import { CartProvider } from "@/contexts/CartContext";
config.autoAddCss = false;

import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { WishlistProvider } from "@/contexts/WishListContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "LWSkart",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { lang } }) {
  await connectDB();
  const session = await auth();
  return (
    <html lang={lang || "en"}>
      <body className={poppins.className}>
        <SessionProvider session={session}>
          <CartProvider>
            <WishlistProvider>
              <Header />
              <NavArea lang={lang} />
              {children}
              <Footer />
              <CopyrightInfo />
            </WishlistProvider>
          </CartProvider>
        </SessionProvider>
        <ToastContainer
          position="bottom-center"
          autoClose={5000}
          hideProgressBar={true}
          newestOnTop={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
        />
      </body>
    </html>
  );
}
